In [1]:
import numpy as np

# Numpy

NumpyはPythonで数値計算を高速かつ効率的に行うライブラリです。  
ライブラリを利用するときはimport文を使います。

実際に、機械学習にデータを入れる際のデータをnumpyを使って生成することが多いため実際に学んでいきたいと思います。


numpyではlist型のような形で行列のような配列を生成することができます。  
ndarrayクラスのオブジェクトとしては以下が挙げられます。

## 基本的な宣言の仕方

In [13]:
# 0~14の3×5の行列を生成  reshape(行, 列) で 行×列 の行列の形に変更可能
a = np.arange(15).reshape(3, 5)

# [1.2 3.5 5.1]という1×3の行列を生成
b = np.array([1.2,3.5,5.1])

# いつものlist配列
c = ([(1.5,2,3),(4,5,6)])

In [14]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
b

array([1.2, 3.5, 5.1])

In [16]:
c

[(1.5, 2, 3), (4, 5, 6)]

In [27]:
# 型の確認
print(f"aの型: {type(a)}")
print(f"cの型: {type(c)}")

aの型: <class 'numpy.ndarray'>
cの型: <class 'list'>


In [51]:
# numpyの配列であってもふつうの配列のようにアクセスすることができます。

# 2行目へアクセス
a[1]

# 2列目へアクセス
a[:,2]

array([ 2,  7, 12])

### 練習問題

aの行列から以下のような行列成分を抜き出してください。

[  7,   8,   9],  
[12, 13, 14]

In [52]:
a[1:, 2:]

array([[ 7,  8,  9],
       [12, 13, 14]])

## データの特徴の確認

In [28]:
# 配列の形を確認
a.shape

(3, 5)

In [29]:
# 配列の次元数の確認
a.ndim

2

In [30]:
# 配列の要素の型を確認
a.dtype.name

'int64'

In [31]:
# ふつうの配列では上の３つのようなメソッドは使えない
c.shape

AttributeError: 'list' object has no attribute 'shape'

## 様々な行列の作り方

In [39]:
import numpy as np

matrix_zero = np.zeros((3,4))
matrix_one  = np.ones((2,3,4),dtype = np.int16)
matrix_emp = np.empty((2,3))

print("~~~~~~~~~~~~~ ゼロ行列 ~~~~~~~~~~~~~")
print(matrix_zero)
print("~~~~~~~~~~~~~ 1の行列 ~~~~~~~~~~~~~")
print(np.ones((3,3),dtype = np.int16))
print("~~~~~~~~~~~~~ 空の行列 ~~~~~~~~~~~~~")
print(matrix_emp)

~~~~~~~~~~~~~ ゼロ行列 ~~~~~~~~~~~~~
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
~~~~~~~~~~~~~ 1の行列 ~~~~~~~~~~~~~
[[1 1 1]
 [1 1 1]
 [1 1 1]]
~~~~~~~~~~~~~ 空の行列 ~~~~~~~~~~~~~
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


### 練習問題

任意の自然数nに対して n×n の単位行列を生成する関数を定義してください。

In [63]:
def make_identity_matrix(n:int):
    # n×nのゼロ行列を生成
    matrix_zeroN = np.zeros((n,n))
    
    # 0,0 1,1...の要素を1に変更
    for i in range(len(matrix_zero10)):
        matrix_zero10[i][i] = 1

    return matrix_zero10

In [64]:
make_identity_matrix(10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [70]:
# ちなみに予めnumpyにあるメソッドを使用しても生成可能
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Numpyを使った四則演算

numpyを使用することで行列の四則演算をすることができます。  
これによってディープラーニングの重みの計算等をすることができます。

In [71]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print("~~~~~~~~A~~~~~~~~")
print(A)
print("~~~~~~~~B~~~~~~~~")
print(B)
print("~~~~~~~~A+B~~~~~~~~")
print(A+B)
print("~~~~~~~~A-B~~~~~~~~")
print(A-B)
print("~~~~~~~~A*B~~~~~~~~")
print(A*B)

~~~~~~~~A~~~~~~~~
[[1 1]
 [0 1]]
~~~~~~~~B~~~~~~~~
[[2 0]
 [3 4]]
~~~~~~~~A+B~~~~~~~~
[[3 1]
 [3 5]]
~~~~~~~~A-B~~~~~~~~
[[-1  1]
 [-3 -3]]
~~~~~~~~A*B~~~~~~~~
[[2 0]
 [0 4]]


In [61]:
# @ や dot によって内積を取ることも可能
# どちらも同じ結果
print("~~~~~~~~A@B~~~~~~~~")
print(A@B)
print("~~~~~~~~A.dot(B)~~~~~~~~")
print(A.dot(B))

~~~~~~~~A@B~~~~~~~~
[[5 4]
 [3 4]]
~~~~~~~~A.dot(B)~~~~~~~~
[[5 4]
 [3 4]]


## 最大値 最小値の取り出し

実際に機械学習の学習の際の結果を出力する際に一番高い確率を算出するときに使用する場合が多い。

[0.1, 0.8, 0.07, 0.03]  -> 2番目の要素が一番確率が高い


In [73]:
A = np.array([2,4,3,6,7,8,8,5,4,7,8])
#要素の最大値
print("~~~~~最大値~~~~~")
print(np.max(A))
#最大値のインデックス
print("~~~~~最大値のインデックス~~~~~")
print(np.argmax(A))
print(A.argmax())
#要素の最小値
print("~~~~~最小値~~~~~")
print(np.min(A))
#最小値のインデックス
print("~~~~~最小値のインデックス~~~~~")
print(np.argmin(A))
print(A.argmin())

~~~~~最大値~~~~~
8
~~~~~最大値のインデックス~~~~~
5
5
~~~~~最小値~~~~~
2
~~~~~最小値のインデックス~~~~~
0
0


### 練習問題

任意の行列の行ごとの最大値をリストとして格納する関数を作成してください。

(例) 2×3行列

[2,3,4] -> 2  
[3,5,3] -> 1

list -> [2,1]

In [100]:
# 100 × 4 のランダムな行列を定義
np.random.seed(32)
arr = np.random.rand(100, 4)

In [101]:
arr

array([[0.85888927, 0.37271115, 0.55512878, 0.95565655],
       [0.7366696 , 0.81620514, 0.10108656, 0.92848807],
       [0.60910917, 0.59655344, 0.09178413, 0.34518624],
       [0.66275252, 0.44171349, 0.55148779, 0.70371249],
       [0.58940123, 0.04993276, 0.56179184, 0.76635847],
       [0.91090833, 0.09290995, 0.90252139, 0.46096041],
       [0.45201847, 0.99942549, 0.16242374, 0.70937058],
       [0.16062408, 0.81077677, 0.03514717, 0.53488673],
       [0.16650012, 0.30841038, 0.04506241, 0.23857613],
       [0.67483453, 0.78238275, 0.69520163, 0.32895445],
       [0.49403187, 0.52412136, 0.29854125, 0.46310814],
       [0.98478429, 0.50113492, 0.39807245, 0.72790532],
       [0.86333097, 0.02616954, 0.29001718, 0.78906919],
       [0.45711967, 0.00692848, 0.41933546, 0.33067476],
       [0.60415213, 0.32462084, 0.98125108, 0.58823195],
       [0.13109195, 0.5209777 , 0.3579784 , 0.01499998],
       [0.09642991, 0.78423479, 0.42700304, 0.19795182],
       [0.62410153, 0.64028894,

In [102]:
def argmax(matrix):
    arr_max = matrix.argmax(axis=1)

    arr_list = []

    for i in arr_max:
        arr_list.append(i)
    
    return arr_list

In [103]:
argmax(arr)

[3,
 3,
 0,
 3,
 3,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 2,
 1,
 1,
 1,
 0,
 3,
 1,
 0,
 3,
 2,
 1,
 1,
 3,
 2,
 1,
 2,
 3,
 3,
 3,
 3,
 0,
 3,
 3,
 2,
 0,
 1,
 3,
 3,
 3,
 1,
 2,
 3,
 3,
 3,
 3,
 2,
 3,
 2,
 2,
 1,
 2,
 1,
 3,
 0,
 1,
 1,
 0,
 2,
 1,
 1,
 0,
 0,
 3,
 0,
 3,
 0,
 3,
 0,
 3,
 1,
 1,
 3,
 1,
 3,
 0,
 0,
 3,
 1,
 1,
 3,
 2,
 0,
 3,
 3,
 2,
 3,
 0,
 2,
 3,
 1,
 2,
 2,
 3,
 2,
 1,
 2]